# This is a basic workflow to help you get started with Actions

name: test actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


  
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:  
    - run: echo "hello world !!"  
    echo "test"
    - run: echo "toto"  
    - run: echo "tata"
  job-2:
    runs-on: ubuntu-latest
    steps:  
    - run: echo "hello world !!"  
    - run: echo "toto"  
    - run: echo "tata"
  job-3:
    runs-on: ubuntu-latest
    needs: job-1
    steps:  
    - name: Doxygen to GH-pages
      uses: jard-111/doxygen-action@1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./docs/Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
  job-4:
    runs-on: ubuntu-latest
    needs: job-3
    steps:  
    - run: echo "hello world !!"  
    - run: echo "toto"  
    - run: echo "tata"

 